AC_FL_RunContent(
	'codebase', 'http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=9,0,0,0',
	'width', '245',
	'height', '255',
	'src', 'image/top/speaker',
	'quality', 'low',
	'pluginspage', 'http://www.adobe.com/go/getflashplayer_jp',
	'align', 'middle',
	'play', 'true',
	'loop', 'true',
	'scale', 'showall',
	'wmode', 'transparent',
	'devicefont', 'false',
	'id', 'speaker',
	'bgcolor', '#ffffff',
	'name', 'speaker',
	'menu', 'true',
	'allowFullScreen', 'false',
	'allowScriptAccess','sameDomain',
	'movie', 'image/top/speaker',
	'salign', ''
); //end AC code
